djeedai/bevy_hanabi

CHANGELOG.md, Cargo.toml, README.md, examples/activate.rs, examples/circle.rs, examples/gradient.rs, examples/spawn.rs, examples/spawn_on_command.rs, src/bundle.rs, src/lib.rs, src/spawn.rs
Allows resetting, activation, and deactivation of spawners.
=> Spawn on command

examples/activate.rs, examples/circle.rs, examples/gradient.rs, examples/spawn.rs, examples/spawn_on_command.rs
- All examples can be closed with ESC
- All examples have `WorldInspectorPlugin`
- All examples have named objects
=> Standardize examples

CHANGELOG.md, Cargo.toml, README.md, examples/random.rs, src/plugin.rs, src/render/mod.rs, src/spawn.rs
Now `Value::Uniform` actually randomizes.
=> Randomization for randomized spawning parameters

.github/workflows/ci.yaml, CHANGELOG.md, Cargo.toml, README.md, examples/2d.rs, src/lib.rs, src/plugin.rs, src/render/effect_cache.rs, src/render/mod.rs
For now, exactly one of the features "2d" and "3d" must be enabled.
=> Added 2D camera support

CHANGELOG.md, Cargo.toml, README.md, examples/2d.rs, examples/activate.rs, examples/circle.rs, examples/force_field.rs, examples/gradient.rs, examples/random.rs, examples/spawn.rs, examples/spawn_on_command.rs, src/plugin.rs, src/render/effect_cache.rs, src/render/mod.rs
Switch the library to build against Bevy v0.7 instead of v0.6, and
disable all plugins in examples as they're not ported to v0.7 yet.
=> Upgrade to Bevy v0.7

src/asset.rs, src/lib.rs, src/modifiers.rs, src/render/mod.rs, src/render/particles_update.wgsl
#31 Added ParticleLifetimeModifier.
=> Added ParticleLifetimeModifier

CHANGELOG.md, Cargo.toml, examples/2d.rs, examples/activate.rs, examples/circle.rs, examples/force_field.rs, examples/gradient.rs, examples/lifetime.rs, examples/random.rs, examples/spawn.rs, examples/spawn_on_command.rs, src/gradient.rs, src/lib.rs, src/modifiers.rs, src/plugin.rs, src/render/aligned_buffer_vec.rs, src/render/effect_cache.rs, src/render/mod.rs, src/render/particles_render.wgsl, src/render/particles_update.wgsl, src/render/pipeline_template.rs, src/test_utils.rs
=> Update to Bevy 0.8

Cargo.toml, run_examples.bat
Add some missing example to `run_examples.bat`, and all the missing examples to `Cargo.toml`.
=> Add examples to `run_examples.bat` and `Cargo.toml`

src/modifier/init.rs, src/modifier/render.rs, src/modifier/update.rs
Validate the shader code emitted by all modifiers by parsing it with naga.
=> Validate code from modifiers with naga

examples/2d.rs, examples/billboard.rs, examples/spawn.rs, src/lib.rs
Animate some examples to better demonstrate some effects.
=> Add some animation to some examples

Cargo.toml
=> Use less restrictive bytemuck dependency

.github/workflows/ci.yaml, src/gradient.rs, src/graph/mod.rs, src/modifier/render.rs
Run cargo fmt and clippy during CI.
=> Check format and clippy in CI

src/attributes.rs, src/graph/expr.rs, src/lib.rs, src/modifier/init.rs, src/modifier/render.rs, src/modifier/update.rs, src/render/vfx_init.wgsl, src/render/vfx_render.wgsl, src/render/vfx_update.wgsl
Add a random operator and its associated expression to generate uniformly-distributed random values in `[0:1]`.
=> Add `BuiltInOperation::Rand`

examples/2d.rs, examples/activate.rs, examples/billboard.rs, examples/circle.rs, examples/expr.rs, examples/force_field.rs, examples/gradient.rs, examples/init.rs, examples/instancing.rs, examples/lifetime.rs, examples/multicam.rs, examples/portal.rs, examples/random.rs, examples/spawn.rs, examples/visibility.rs, src/lib.rs
Fix all examples to initialize the age of particles. Otherwise they will never die and won't despawn.
=> Initialize the age of particles in examples

Cargo.toml, examples/2d.rs, examples/activate.rs, examples/billboard.rs, examples/circle.rs, examples/expr.rs, examples/firework.rs, examples/force_field.rs, examples/gradient.rs, examples/init.rs, examples/instancing.rs, examples/lifetime.rs, examples/multicam.rs, examples/portal.rs, examples/random.rs, examples/spawn.rs, examples/spawn_on_command.rs, examples/visibility.rs
Re-enable inspector ahead of v0.7.0 release.
=> Prerelease fixes for v0.7.0

README.md
=> Fix outdated README

CHANGELOG.md, src/graph/expr.rs
Augment `Expr` with many built-in WGSL functions.
=> Add many more built-in functions

CHANGELOG.md, src/graph/expr.rs
Add a new expression to cast an operand expression to another type.
=> Add cast expression

CHANGELOG.md, src/graph/expr.rs
Add the `BinaryOperator::Remainder` operator calculating the remainder of the division of two expressions.
=> Add remainder operator `%` expression

src/graph/expr.rs
There's currently no way to combine multiple dynamic scalar expressions into a scalar. This causes many problems, including not being able to convert an angle to a 2D vector, as demonstrated in the new doctests. This commit adds a new binary operator, `vec2`, and a new ternary operator, `vec3`, for this. Both operators work on all scalar types.
=> Add dynamic `vec2` and `vec3` constructors to the expression grammar.

src/attributes.rs
- Remove dead code in `VectorType::align()` trying to handle invalid vector type with rank not in 2..=4.
- Add missing panic in `MatrixType::new()` when trying to create invalid matrix with number of rows or columns not in 2..=4.
- Add more tests to validate `ValueType` and related types.
=> Minor fixes in `ValueType` and co.

.github/workflows/ci.yaml
Linux PPA drivers keep producing errors.
=> Run GPU CI tests on Windows agent with DX12

CHANGELOG.md, docs/migration-v0.10-to-v0.11.md, src/attributes.rs, src/lib.rs
Also fix a few bugs in comments and CHANGELOG.
=> Add migration guide for v0.11

.github/workflows/ci.yaml
This fixes an issue with the latest llvm_profparser.
=> Upgrade tarpaulin to 0.31.2

README.md, src/lib.rs
I'm just going through your example – thanks a lot, I really enjoy learning WGSL through bevy_hanabi! One little thing that confused me: the comment states that there is a radius of "2 units", however the code says it's 0.5. Is there something I didn't get or is this a simple typo?
=> Possible typo?

src/render/mod.rs
Silently skip (with a debug log) any effect if one of the compute pipelines is queued for creation but was not created yet. This prevents a panic in `wgpu` and ensure we can retry later once all pipelines are ready.
Fixes #428
=> Silently skip effects if pipeline creation pending

CHANGELOG.md, src/graph/expr.rs
Add a few missing expressions to the Expression API.
=> Add expr: `acos`, `asin`, `atan`, `atan2`, `round`

src/render/mod.rs
Hanabi uses the `Added<CompiledEffect>` query filter in order to determine when particle effects should be added to the `added_effects` table. But, if the particle effect asset isn't loaded at the time that query runs, Hanabi will skip adding the particle effect to that table. Because the `Added<CompiledEffect>` query filter will only match particle effects once, once the particle effect asset finally loads, it's too late to add it to the `added_effects` list. Thus it will never show up.
This patch fixes the issue by adding effects that are newly added but not yet fully loaded to a `pending_effects` list. The `added_effects` loop is modified to not only take into account effects that match the `Added<CompiledEffect>` filter but also effects in the `pending_effects` list. Effectively, that …
=> Try reextracting next frame if an effect isn't loaded when Hanabi first encounters it.

src/lib.rs
This is a small quality of life improvement to allow writing queries which detect when the underlying `EffectAsset` changed.
=> Implement `AsAssetId` for `ParticleEffect`

src/render/mod.rs
=> Silence pesky warning
