djeedai/bevy_hanabi

- src/render/mod.rs
Ensure particles hidden behind geometry are not rendered. This fixes the
rendering of the `circle` example showing particles always on top.
> Fix depth comparison function

- CHANGELOG.md
- src/render/mod.rs
Ensure enough workgroups are dispatched to process all particles,
rounding up to the number of particles to avoid truncating the last few
ones.
> Fix workgroup calculation

- CHANGELOG.md
- src/gradient.rs
- src/render/mod.rs
Make the `GradientKey::ratio` field private, and add a `ratio()` read-only
accessor, to prevent the user from modifying the ratio of a key already
inserted into a `Gradient` and break the internal sorting.
> Make `GradientKey::ratio` private

- CHANGELOG.md
- src/lib.rs
- src/modifiers.rs
- src/render/mod.rs
Rename the `ToWgslFloat` trait into `ToWgslString` to make it more
generic, and implement it for `Vec2` / `Vec3` / `Vec4` to make it easier
to format vectors. Also rename the `to_float_string()` trait method into
`to_wgsl_string()` for consistency.
> Rename float trait to WGSL and impl vec

- CHANGELOG.md
- README.md
- examples/activate.rs
- examples/circle.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
- src/lib.rs
- src/modifiers.rs
- src/spawn.rs
Particles can now start with a random velocity in the radial direction. I separated this from randomness of spawner parameters because that would require an RNG to maintained and passed around in the CPU, while this just needed a small shader modification.
> Added support for random velocity

- CHANGELOG.md
- Cargo.toml
- README.md
- src/render/effect_cache.rs
- src/render/mod.rs
Update the library to use tighter Bevy depedencies, removing the general
`bevy/render` and instead depending on `bevy/bevy_core_pipeline` and
`bevy/bevy_render` only.
> Tighter Bevy dependencies

- CHANGELOG.md
- Cargo.toml
Add the `derive` feature to the `bytemuck` dependency, which used to
build without but is having troubles now and confuses the Rust compiler
unless explicitly added, for some reason. Since this looks more correct,
and probably shouldn't have worked before, add the feature.
> Fix missing `bytemuck` derive feature

- .github/workflows/ci.yaml
- CHANGELOG.md
- Cargo.toml
- README.md
- release.md
- src/lib.rs
- src/plugin.rs
- src/render/effect_cache.rs
- src/render/mod.rs
Make the `2d` and `3d` features purely additive, allowing for both to be
selected at once, to enable rendering through both 2D and 3D cameras.
Aside from being more versatile, this avoids a series of issues with
`docs.rs` and `cargo publish` where `--all-features` was previously
forbidden, making it difficult/impossible to use them correctly. This
also follows the official Rust guidelines on features, which state all
features must be strictly additive.
> Switch to additive `2d`/`3d` features

- CHANGELOG.md
- Cargo.toml
- examples/spawn.rs
- src/render/aligned_buffer_vec.rs
- src/render/mod.rs
Ensure the spawner parameters are aligned based on actual GPU
constraints of the host, to enable binding the data block without error.
Bug: #26
> Align spawner params with GPU constraints

- .github/workflows/ci.yaml
- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/render/aligned_buffer_vec.rs
- src/test_utils.rs
Add a test for `AlignedBufferVec<T>` to ensure the data is properly
written to the GPU, by reading it back to compare locally. This mocks a
Bevy render device and queue backed by a real physical WGPU device.
> Add GPU test for `AlignedBufferVec<T>`

- src/asset.rs
- src/lib.rs
The `InitModifier` and `UpdateModifier` traits were impossible to implement because the `InitLayout` and `UpdateLayout` struct were private.
This PR makes these structs publicly available. Shouldn't break any existing code that I'm aware of.
> Made the InitLayout and UpdateLayout public

- CHANGELOG.md
- examples/2d.rs
- src/asset.rs
- src/lib.rs
- src/plugin.rs
- src/render/mod.rs
- src/spawn.rs
Add a new field `EffectAsset::z_layer_2d` holding the Z coordinate of
the layer at which particles are rendered in 2D mode. Also add a new
field `ParticleEffect::z_layer_2d` to override this value on a
per-instance basis.
Reflect both `EffectAsset` and `ParticleEffect`, allowing to tweak the
`z_layer_2d` value on a per-instance basis with the egui inspector in
the `2d.rs` example, to show the effect of this Z layer feature.
Bug: #28
> Enable setting the Z layer for 2D particles

- CHANGELOG.md
- src/render/mod.rs
- src/render/particles_update.wgsl
Take into account the `GlobalTransform` of the `Entity` holding the
`ParticleEffect` to emit particles.
Fixes #42
> Handle rotation of emitter

- CHANGELOG.md
- README.md
- src/lib.rs
- src/modifiers.rs
- src/render/particles_update.wgsl
Add a new position modifier `PositionCone3dModifier` which spawns
particle inside a truncated 3D cone, with a velocity directed from the
apex toward the base.
Change the `particles_update.wgsl` code and all other modifiers to take
into account the transform of the emitter `Entity` directly in the
`init_pos_vel()` method, so they can apply it most efficiently.
> Add `PositionCone3dModifier` for directional emit

- CHANGELOG.md
- src/lib.rs
- src/material.rs
- src/modifiers.rs
- src/plugin.rs
- src/render/effect_cache.rs
- src/render/mod.rs
Ensure all profiling GPU markers have a name starting with the `hanabi:` prefix, to group them in _e.g._ RenderDoc and make it easier to find Hanabi-related GPU resources.
> Prefix all profiling GPU markers with `hanabi:`

- CHANGELOG.md
- src/lib.rs
- src/plugin.rs
- src/render/effect_cache.rs
- src/render/mod.rs
Ensure all GPU resources associated with a `ParticleEffect` instance are cleared when that component instance is despawned. This fixes a bug where buffers are reused for a different instance, possibly giving the impression that the effect continues to simulate even though it's despawned.
Fixes #45
> Clean-up GPU resources on `ParticleEffect` despawn

- CHANGELOG.md
- README.md
- examples/2d.rs
- examples/activate.rs
- examples/billboard.rs
- examples/circle.rs
- examples/force_field.rs
- examples/gradient.rs
- examples/lifetime.rs
- examples/random.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
- src/asset.rs
- src/lib.rs
- src/modifier/init.rs
- src/modifier/mod.rs
- src/modifier/render.rs
- src/modifier/update.rs
- src/render/mod.rs
- src/render/particles_update.wgsl
Move all the modifiers under a top-level `modifier` module, and further group them based on the phase they modify under three sub-modules `init`, `update`, and `render`.
Clean-up the `ForceFieldModifier` with various renames for clarity and consistency, and added documentation.
> Reorganize all modifiers into modules

- CHANGELOG.md
- src/lib.rs
- src/material.rs
- src/render/effect_cache.rs
- src/render/mod.rs
Hide the `EffectCacheId` type, which is only used internally and has no value to the API user.
> Make `EffectCacheId` private

- src/lib.rs
Ensure the default (fallback) position code of the update compute shader takes into account the transform of the effect, like do all init modifiers.
> Fix ignored transform in default position code

- src/render/mod.rs
- src/render/particles_update.wgsl
Use a single common bind group for both the particle buffer containing the actual per-particle data, and the indirect buffer containing the index of the particles to render in sorted order. This frees up a bind group for other uses in the update compute shader, while keeping their number under the wgpu default limit of 4.
> Single bind group for particles and indirection

- src/modifier/update.rs
- src/test_utils.rs
Fix a bug where `ForceFieldModifier::new()` can be called with an iterator generating one too many sources, making the call panic in an unexpected way.
> Fix off-by-one error in `ForceFieldModifier::new()`

- src/render/aligned_buffer_vec.rs
- src/render/mod.rs
Ensure that `AlignedBufferVec` items are properly aligned according to the WGSL language rules.
Fixes #55
> Fix item alignment for GPU in `AlignedBufferVec`

- CHANGELOG.md
- src/render/mod.rs
Ensure the render pipeline reads the `Msaa::samples` value defined by the user instead of assuming a value.
Fixes #59
> Respect user-defined MSAA setting

- CHANGELOG.md
- src/render/effect_cache.rs
Fix a bug in the effect cache buffer insertion when an existing index was free. This was causing some panic when an effect was removed then another inserted in the same frame, causing the batched effects to be out of sync with the actual GPU buffers.
Fixes #60
> Fix effect cache buffer insertion

- CHANGELOG.md
- src/render/effect_cache.rs
- Fix indirect buffer binding calculation, which results in panic when the capacity is small compared to the spawn count.
- Fix `pop_free_slice()` to prevent allocating over a range too small, and to split free slices in case the new requested size is strictly smaller than the best free slice, so that no space is wasted.
Fixes #68
> Fix bugs in `EffectCache`

- CHANGELOG.md
- Cargo.toml
- examples/instancing.rs
- run_examples.bat
- src/render/effect_cache.rs
- src/render/mod.rs
Batching of compatible effects (and in particular, multiple instances of the same effect) is currently broken due to the inability for a particle to tell which effect it's associated with, and therefore which `GpuSpawnerParams` struct it should index.
To prevent batching to trigger, set the minimum buffer capacity to 1 particle, which effectively means each effect will get a dedicated GPU buffer that just fits it, preventing another effect from using the same buffer, and effectively disabling batching.o
Bug: #73
> Disable broken effect batching

- CHANGELOG.md
- examples/spawn.rs
- src/lib.rs
- src/plugin.rs
- src/render/aligned_buffer_vec.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/particles_init.wgsl
- src/render/particles_render.wgsl
- src/render/particles_update.wgsl
- src/render/vfx_indirect.wgsl
Split the init and update compute passes. The init pass is dispatched from CPU
when new particles need to be spawned, while the update pass is now GPU-driven
(indirect dispatch). The render pass is also modified to be GPU-driven
(indirect render), avoiding the unnecessary rendering of dead particles
previously occurring.
Add a new `instancing` example demonstrating many instances of the same effect
used in parallel.
Fixes #19
> Split init/update phases + indirect dispatch/render

- src/lib.rs
- src/render/aligned_buffer_vec.rs
- src/render/mod.rs
Move the `next_multiple_of()` filler utility into a more central location in the crate, now that it's used in multiple places.
> Move `next_multiple_of()` into `lib.rs`

- CHANGELOG.md
- src/lib.rs
The `ParticleEffect::spawner()` method is used internally to initialize the spawner of a `ParticleEffect` from the one of its `EffectAsset`. It was not designed to be used publicly and its usage is somewhat confusing. Hide the method by marking it as `pub(crate)`.
> Mark `ParticleEffect::spawner()` as private

- CHANGELOG.md
- run_examples.bat
- src/asset.rs
- src/lib.rs
- src/modifier/render.rs
Rename the oddly-named `RenderLayout::size_color_gradient` into the more understandable `RenderLayout::lifetime_size_gradient`.
Add a few tests for `RenderLayout`.
Reorder examples in `run_examples.bat` by feature set.
> `RenderLayout::{size_color,lifetime_size}_gradient`

- CHANGELOG.md
- src/render/mod.rs
Fix a panic in the render module when no effect exist, and the queuing earlied out before initializing some GPU resources.
Fixes #90
> Fix panic when no effect exists

- CHANGELOG.md
- examples/gradient.rs
- src/render/mod.rs
Ensure HDR cameras (`Camera::hdr == true`) can be used for rendering, by selecting the proper render target format.
Fixes #92
> Add support for HDR cameras

- src/lib.rs
- src/render/mod.rs
Clean-up a bit the prepare pass by moving some book-keeping code into the impl of `EffectsMeta` itself. This makes things a bit more bite-sized and easier to reason about and later test.
> Move some code into `EffectsMeta` methods

- src/lib.rs
- src/plugin.rs
- src/render/mod.rs
Add a simulation sub-graph to the main render graph, driven by the `VfxSimulateDriverNode` render node. This sub-graph is run once per frame, before any camera.
Fixes #102
> Run simulation render graph once per frame

- src/gradient.rs
- src/test_utils.rs
Add a new utility trait `AbsDiffEq` allowing to extend the use of the testing macro `assert_approx_eq!()` to various scalar and vector floating-point math types.
> Improve testing with `AbsDiffEq`

- CHANGELOG.md
- src/render/mod.rs
- src/test_utils.rs
Fix bind groups not re-created correctly when an effect is despawned in the same frame as another effect is spawned.
Add a partial workaround for the `vfx_indirect.wgsl` shader accessing GPU buffers in order from index 0, which requires all GPU particle buffers to be in use without any gap. The partial workaround first destroys buffers for de-allocated effects, before re-creating new buffers for newly-spawned ones. This is not perfect, because this doesn't account for gaps when more buffers are de-allocated than created in the same frame, in which case `vfx_indirect` accesses the first N buffers, but some of them are not in use and some in use are skipped. We're missing an indirection here.
Fixes #106
> Fix same-frame despawn/respawn

- Cargo.toml
Align with the version used by Bevy 0.9.
> Update `ron` dependency to `0.8`

- CHANGELOG.md
- src/render/effect_cache.rs
- src/render/mod.rs
Fix a regression in 2D rendering introduced in #107, and fix 2D rendering not using indirect (GPU-driven) rendering.
> Fix regression in 2D rendering

- CHANGELOG.md
- src/asset.rs
Remove the `Resource` derive from `EffectAsset`, which makes little sense on an asset.
> Remove `#[derive(Resource)]` from `EffectAsset`

- .github/workflows/ci.yaml
- CHANGELOG.md
- src/gradient.rs
Add implementations of the `Reflect`, `FromReflect`, `Serialize`, and `Deserialize` traits for `Gradient<T>`.
> Make `Gradient<T>` reflected and serializable

- Cargo.toml
- examples/instancing.rs
- src/render/aligned_buffer_vec.rs
- src/render/buffer_table.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/test_utils.rs
Fix the dispatch indirect and render dispatch buffers being overwritten on
re-allocating. The buffers are accessed both by the CPU to allocate new effects
and by the GPU to update existing effect. On re-allocating, the CPU to GPU copy
was overwriting all previous GPU changes, which resulted in all spawned effect
appearing to restart.
This change introduces a new `BufferTable` data structure with a free list,
which helps carefully interleave CPU-to-GPU upload writes and GPU-side
mutations so they never overwrite each other.
The `instancing` example has been updated to be interactive, allowing the user
to add more effects with SPACE and remove existing effects with DELETE. This
shows the bug is fixed and users can spawn and despawn effect instances without
affecting the other spawned …
> Fix particle resetting after spawn

- Cargo.toml
- examples/2d.rs
- examples/activate.rs
- examples/billboard.rs
- examples/circle.rs
- examples/firework.rs
- examples/force_field.rs
- examples/gradient.rs
- examples/instancing.rs
- examples/lifetime.rs
- examples/multicam.rs
- examples/random.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
Upgrade the examples to use the newer v0.17 of `bevy-inspector-egui` which comes with built-in support for `Option<T>` for reflected type, allowing to reflect _e.g._ the `Spawner` of a `ParticleEffect` to be able to dynamically activate and deactivate it in examples.
> Upgrade examples to `bevy-inspector-egui` v0.17

- src/render/mod.rs
- Remove unused field from `EffectsMeta`
- Group GPU limits and sizes in a cache
- De-duplicate 2d/3d view drawing
> Tidy up internal code

- CHANGELOG.md
- examples/instancing.rs
- src/render/buffer_table.rs
Fix a panic on `unwrap()` after N > 1 effects are despawned and M < N effects are re-spawned. The internal buffer table was using a different logic from the effect cache, so indices where going out of sync.
Change the `instance.rs` example to spawn effects in random positions. Add a (disabled) stress test to that example, which randomly spawns and despawns effects quickly to uncover bugs more easily.
Fixes #123
> Fix panic on respawn

- src/render/buffer_table.rs
- src/render/mod.rs
- src/test_utils.rs
Ensure we get a modern implementation, normally Vulkan as we run CI on Linux agents, which supports the features we need for Hanabi like compute shaders. This prevent CI agents from failing some GPU tests.
> Request `PRIMARY` backends in mock renderer

- .github/workflows/ci.yaml
Properly cache `.crates.toml` and `.crates2.json` as recommended by the cargo team here: https://github.com/rust-lang/cargo/issues/11513. This ensures installed cargo binaries are cached, and restored correctly.
Remove the `--force` flag from the tarpaulin install, to use the cached version if available and speed up the coverage build.
> Fix tarpaulin caching on CI

- CHANGELOG.md
- examples/instancing.rs
- examples/lifetime.rs
- examples/spawn.rs
- src/lib.rs
- Fix the `spawn` example on larger resolutions. (#110)
- Change the color gradient of the `lifetime` example for clarity.
- Allow the BACKSPACE key in addition of the DELETE key in the `instancing` example, for useability on macOS.
Fixes #110
> Improve a few examples

- src/lib.rs
- src/render/mod.rs
Delete fields storing the shader's WGSL code, which duplicates the batching key functionality of the `ShaderCache`. The configured shader handles saved in `ParticleEffect` and `ExtractedEffect` already guarantee the unicity of the effect batches.
> Don't cache shader code unnecessarily

- CHANGELOG.md
- Cargo.toml
- examples/instancing.rs
- examples/portal.rs
- src/asset.rs
- src/gradient.rs
- src/lib.rs
- src/modifier/render.rs
- src/render/mod.rs
- src/render/vfx_render.wgsl
Transition the render shader too to the `RenderContext` architecture with render modifiers directly writing shader code to a template, like for the init and udpate contexts. This unlocks more complex render modifiers like orienting particles alongside their velocity.
Add a new `OrientAlongVelocityModifier` to orient particles along their velocity to allow creating streaks / sparkles.
Fixes #133
> Switch render shader to `RenderContext`

- src/attributes.rs
- src/graph/mod.rs
Ensure `Value` and `ValueType` return a type layout confirming to the WGSL specification by using naga as a reference.
> WGSL-conforming `Value` and `ValueType`

- src/attributes.rs
- src/graph/mod.rs
- src/render/effect_cache.rs
Add a default value to `Attribute` so that the rendering shader can initialize its variables to those default values in case they're not explicitly used in the particle's attribute layout. This is also generally useful to initialize in the future an input/output pin of a shader node.
> Add default value to `Attribute`

- Cargo.toml
- examples/2d.rs
- examples/activate.rs
- examples/billboard.rs
- examples/circle.rs
- examples/firework.rs
- examples/force_field.rs
- examples/gradient.rs
- examples/instancing.rs
- examples/lifetime.rs
- examples/multicam.rs
- examples/portal.rs
- examples/random.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
- src/attributes.rs
- src/lib.rs
- src/modifier/init.rs
- src/modifier/render.rs
- src/modifier/update.rs
- src/plugin.rs
- src/render/mod.rs
- src/render/vfx_init.wgsl
- src/render/vfx_update.wgsl
- src/test_utils.rs
**The update is blocked by bevy-inspector-egui, but not really since it only affects examples and can easily be disabled**
To run examples: Disable inspector in the Cargo toml and the example code
I only ran examples and tests, they all seemed to work fine, but I'm not sure if any features have been missed in these. I did have some weird errors when closing windows, and some of the tests seemed to eat a lot of GPU resources, but I'm not sure if this is new behavior.
Some things to note:
- Shaders now need to specify global variables with `const` instead of `let`.
- You can no longer redefine a variable name with `let`.
- The set EffectSystems::ExtractEffects is unused, and only lives in the ExtractSchedule, so it can probably be removed
- There is a new field on `RenderPipelineDescriptor` …
> Update to bevy 0.10

- src/modifier/init.rs
The position inside the cone was affected by the transform, but since the w component of the position was set to 1 the transform was affecting adding the translation. However this also gets done when it's rendered I believe, so the translation was added twice.
However I'm not sure why the position (and the speed in the next part) were affected by the transform at all. The code for InitPositionCircleModifier does not use transform, though the InitVelocityCircleModifier does, so maybe this change is the most correct? I can't seem to see any observable difference at all whether I keep it or remove it entirely, but maybe I'm missing something. Though I think maybe neither of them should be affected by the transform?
But maybe I'm missing something here.
Fixes #152
> Fixed PositionCone3dModifier placing particles at twice the translation

- CHANGELOG.md
- Cargo.toml
- examples/init.rs
Add a new example demonstrating the various position initializing modifiers, and showing:
- the bug in cone3d distribution
- the absence of effect of the emitter's rotation on the circle and sphere modifiers
- the correct application of both translation and rotation for the cone3d one
> Add `init.rs` example

- CHANGELOG.md
- README.md
- examples/init.rs
- src/asset.rs
- src/attributes.rs
- src/lib.rs
- src/modifier/init.rs
- src/modifier/render.rs
- src/modifier/update.rs
- src/render/vfx_update.wgsl
Make particle aging and reaping conditional to the presence of the `Attribute::AGE` and `Attribute::LIFETIME`, which are themselves not mandatory anymore (not added by default) but instead depend on the modifier(s) added to the `EffectAsset`.
Add two new modifiers:
- `SetColorModifier` to set the per-particle rendering color on spawn, to a constant value that do not vary with the age/lifetime of the particle.
- `SetSizeModifier` to set the per-particle size on spawn, also not varying after spawning.
This change further improves support for #118.
> Non-mandatory `AGE` and `LIFETIME` attributes

- CHANGELOG.md
- examples/spawn_on_command.rs
- src/attributes.rs
- src/lib.rs
- src/modifier/init.rs
- src/modifier/mod.rs
- src/modifier/render.rs
- src/modifier/update.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/vfx_init.wgsl
Add a new `InitAttributeModifier` to initialize any attribute to a value or property.
Change `Attribute` to be a handle-style wrapper around `&'static AttributeInner`, and enable reflection and serialization. Serialization is performed as the unique attribute name, without the default value.
Add access to properties from init modifiers.
Fix a bug where using `ParticleEffect::with_spawner()` would prevent properties from initializing correctly.
> Add `InitAttributeModifier`

- CHANGELOG.md
- src/render/mod.rs
Ensure effect batching picks the correct texture for the current effect, not the previous one.
Fixes #167
> Fix texture selection in effect batching

- CHANGELOG.md
- src/render/aligned_buffer_vec.rs
- src/render/mod.rs
- src/render/vfx_indirect.wgsl
Manually pad the WGSL `Spawner` struct in the `vfx_indirect.wgsl` compute shader, to ensure that when the struct is accessed as an element of the array in that shader and when that same struct is bound later as an individual item aligned to the storage buffer alignment of the device the two are at the same offset.
Fixes #165
> Pad the WGSL `Spawner` struct to align elements

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/visibility.rs
- run_examples.bat
- run_examples.sh
- src/asset.rs
- src/bundle.rs
- src/lib.rs
- src/render/mod.rs
- src/spawn.rs
- src/test_utils.rs
Allow the effects to be simulated while hidden with the new `SimulationCondition::Always`, which can be assigned to the `EffectAsset::simulation_condition` field. The default value `SimulationCondition::WhenVisible` retain the documented behavior of not simulating any hidden effect (those with a `Visibility::Hidden` or inheriting their parent state).
Added a new `visibility.rs` example showing the behavior of `SimulationCondition::WhenVisible` and `SimulationCondition::Always`.
Fixed a bug where, despite the documentation stating that hidden effects were not simulated, they were nonetheless updated in the background. This possibly could have led to poor performance if many such effects were hidden, which therefore would possibly relate to #67.
Fixes #166
> Enable simulation while hidden

- CHANGELOG.md
- README.md
- examples/portal.rs
- src/lib.rs
- src/modifier/mod.rs
- src/modifier/render.rs
- src/modifier/update.rs
- src/render/vfx_update.wgsl
Add two new update modifiers applying a per-particle acceleration dependent on the particle's position:
- `RadialAccelModifier` applies a radial acceleration in the direction going from the modifier's specified `origin` to the particle current position.
- `TangentAccelModifier` applies an acceleration in the tangent direction obtained as the cross product of the modifier's specified `axis` direction defining the rotation plane normal and the radial direction defined by the particle position (same calculation as `RadialAccelModifier`).
Fixes #97
> Add radial and tangent acceleration modifiers

- README.md
Very small change, should be redundant soon enough anyway when 0.11 is released
> Add hyperlink for wasm issue in README

- src/modifier/init.rs
> Fix attribute name for InitSizeModifier w/ D2

- src/render/vfx_render.wgsl
Both the set size and color render modifiers use these random functions which are missing, I believe. None of the examples use the uniform variant for these modifiers. Bevy supports shader imports now, maybe that should be used here?
> Add rand functions to render shader

- CHANGELOG.md
- src/lib.rs
Change the behavior of effect compiling to always compile all new effects added, irrespective of whether they are visible. This prevent inconsistencies between effects, which was causing a panic.
Bug: #182
> Fix panic when effect spawned hidden is shown

- CHANGELOG.md
- docs/migration-v0.6-to-v0.7.md
- examples/2d.rs
- examples/activate.rs
- examples/billboard.rs
- examples/circle.rs
- examples/expr.rs
- examples/firework.rs
- examples/force_field.rs
- examples/init.rs
- examples/multicam.rs
- examples/portal.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
- src/lib.rs
- src/modifier/render.rs
- src/render/mod.rs
- src/render/vfx_render.wgsl
Add the ability to define the particle size in screen-space logical pixels, instead of world units.
Fix batching of textured and non-textured effects mixed in the same scene.
Bug: #161, #181
> Add screen-space size to render modifiers

- .github/workflows/ci.yaml
Run CI workflow when a PR is converted from Draft status to Ready For Review. Somehow bizarrely this doesn't happen by default.
Also enable manually triggering CI, in case there's a GitHub bug.
> Run CI on PR changed from Draft to Ready

- src/graph/mod.rs
Fix partial and total equality of `ScalarValue` and `VectorValue`, and their hashing computation. For consistency between equality and hashing, values of different types must compare inequal and hash differently, and not cast to each other.
Add a new `cast_eq()` utility allowing to compare scalar and vector values taking into account casting of one type to the other.
> Fix equality and hashing of `Value`

- CHANGELOG.md
- Cargo.toml
- docs/migration-v0.6-to-v0.7.md
- examples/billboard.rs
- examples/circle.rs
- examples/firework.rs
- examples/force_field.rs
- examples/portal.rs
- examples/random.rs
- examples/spawn.rs
- src/lib.rs
- src/modifier/init.rs
- src/modifier/render.rs
- src/spawn.rs
Rename the `spawn::Value` type to `CpuValue` to prevent confusion with the more recent `graph::Value`, which is destined to eventually replace it.
Add `impl Hash for CpuValue` for all floating-point types via a helper trait `FloatHash`. This enables deriving `Hash` for types using `CpuValue<T: FloatHash>`, which at the time of writing includes all uses.
Fix the `Hash` implementation of `SetColorModifier` and `SetSizeModifier`, which were ignoring the `CpuValue` enum variant.
> Rename `spawn::Value` to `CpuValue` and fix `Hash`

- CHANGELOG.md
- docs/migration-v0.6-to-v0.7.md
- examples/spawn.rs
- src/lib.rs
- src/modifier/init.rs
- src/spawn.rs
Delete the `InitSizeModifier`, which is redundant with the more powerful `InitAttributeModifier` and the use of expressions.
Delete `DimValue`, which was only used by that modifier.
> Delete `DimValue` and `InitSizeModifier`

- src/attributes.rs
- src/render/batch.rs
- src/render/effect_cache.rs
- src/render/mod.rs
Add a new internal `Batcher` utility used to batch particle effects for submission to GPU. This replaces the ad hoc code previously used directly in the `prepare_effects()` system, which was hard to maintain and to test, and the source of numerous bugs and regressions.
> Add `Batcher` utility

- CHANGELOG.md
- Cargo.toml
- examples/billboard.rs
- examples/expr.rs
- examples/init.rs
- examples/multicam.rs
- examples/portal.rs
- src/asset.rs
- src/lib.rs
- src/modifier/mod.rs
- src/modifier/output.rs
- src/render/batch.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/vfx_indirect.wgsl
- src/render/vfx_init.wgsl
- src/render/vfx_render.wgsl
- src/render/vfx_update.wgsl
Add a new alternative `SimulationSpace::Local` for simulating particles in the space defined by the `GlobalTransform` attached to the entity of their `ParticleEffect`. This allows applying the effect's transform to all particles after they are simulated. This is opposed to the default global-space simulation offered by `SimulationSpace::Global` where particles are "detached" from the effect when they spawn, and are simulated in the global world space.
Add a new `OrientModifier` and its associated `OrientMode` enum, allowing to orient the particles to face the camera and/or their velocity, both when simulated in local and global space. This unified modifier replaces both the `BillboardModifier` and the `OrientAlongVelocityModifier`.
Bug: #180
> Add local space simulation and `OrientModifier`

- CHANGELOG.md
- src/asset.rs
- src/attributes.rs
- src/graph/expr.rs
- src/graph/node.rs
- src/lib.rs
- src/modifier/accel.rs
- src/modifier/force.rs
- src/modifier/kill.rs
- src/modifier/mod.rs
- src/modifier/output.rs
Make the `RenderContext` on par with the init and update ones, and evaluate the `SimulationSpace` based on the context, as an `eval()` function on the type itself instead of inline inside the shader compiling system. This makes the code more testable, and the compiling system more readable.
> Evaluate `SimulationSpace` in context

- Cargo.toml
- src/lib.rs
- src/render/batch.rs
- src/render/mod.rs
- src/render/vfx_indirect.wgsl
Add a new internal `EffectShader` type containing all the configured shaders of an effect, and an `EffectShaderSource` containing the generated source code for an effect before it's specialized.
Add `naga_oil` as a dev-only dependency, to validate the generated code in tests. This allows specializing the shader code (replace the `#if` _etc._) without having to rely on the entire specialization pipeline feature of Bevy.
> Add `EffectShader` and use `naga_oil` to validate

- CHANGELOG.md
- src/gradient.rs
Add a few utility functions to make it easier to work with `Gradient<T>`, and in particular to build a new gradient:
- `from_keys()` extends the existing `constant()` and `linear()` to a collection of keys;
- `with_key()` and `with_keys()` append to an existing gradient object while consuming it;
- `is_empty()` and `len()` return the expected values for the underlying collection of key points.
> Enchance `Gradient<T>` with more utility functions

- src/render/mod.rs
Only cache GPU limits once on `EffectsMeta` creation. It's unclear what the behavior of Bevy is with respect to GPU adapter dynamic change; most likely this is not supported, so assume the limits cannot change after initial setup.
Rename `SimParamsUniform` to `GpuSimParams` for consistency with other "GPU types".
> Cache GPU limits once at setup

- src/render/mod.rs
Fix a bug where alpha masked effects are emitted with the wrong draw function, causing a panic at runtime.
> Emit alpha masked effects with proper drawfunc

- CHANGELOG.md
- src/properties.rs
Add some extra documentation, examples, and more tests to the `properties` module.
Add a new `PropertyLayout::properties()` function to iterate over the properties of a layout and their offset.
Delete the extra blank line generated by `PropertyLayout::generate_code()` at the end of the generated layout.
> Better document and test the properties module

- CHANGELOG.md
- src/lib.rs
- src/properties.rs
- src/render/mod.rs
Do not panic when the `ParticleEffect` is marked as changed, but the asset handle didn't actually change. Just do a full rebuild instead.
Bug: #228
> Don't panic when effect asset marked as changed

- CHANGELOG.md
- src/graph/mod.rs
I noticed a bug in the `to_wgsl_string` impl for Matrices, where the first element was added twice. I also introduced some basic `From` implementations for the most common matrix formats to be able to test & use matrix values.
Changes:
- Fixed bug in `MatrixValue.to_wgsl_string()`
- Introduced some test cases to verify the fix
- Added `From` implementations for `Mat2`, `Mat3` and `Mat4`
> Fix matrix to wgsl string conversion

- src/lib.rs
- src/render/batch.rs
- src/render/mod.rs
Only save the necessary information in `ParticleInitPipelineKey` instead of an entire copy of both the `ParticleLayout` and `PropertyLayout`.
> Make `ParticleInitPipelineKey` slimmer

- CHANGELOG.md
- src/lib.rs
Implement `ToWgslString` for the following vector types:
- `IVec2`, `IVec3`, `IVec4`
- `UVec2`, `UVec3`, `UVec4`
- `BVec2`, `BVec3`, `BVec4`
> Add missing `ToWgslString` impls for vecs

- CHANGELOG.md
- examples/billboard.rs
- examples/circle.rs
- examples/gradient.rs
- src/lib.rs
- src/modifier/attr.rs
- src/modifier/mod.rs
- src/modifier/output.rs
- src/render/vfx_render.wgsl
Add a new `ImageSampleMapping` enum to customize the way a sample of the image of a `ParticleTextureModifier` is mapped to and modulated with the particle's base color.
The previous behavior was always using the Red channel of the texture as an opacity mask, modulating the sample's Alpha component only. This legacy behavior can be restored with the `ModulateOpacityFromR` value.
The new default is `Modulate`, which corresponds to a full component-wise multiply of all components of the image sample by the particle's base color.
> Customizable image sample mapping

- CHANGELOG.md
- Cargo.toml
- examples/circle.rs
- examples/texutils.rs
- src/attributes.rs
- src/lib.rs
- src/modifier/mod.rs
- src/modifier/output.rs
- src/modifier/position.rs
- src/render/mod.rs
- src/render/vfx_render.wgsl
Add a new `Attribute::SPRITE_INDEX` and a new `FlipbookModifier` to enable spritesheet-based "flipbook" animation of particles.
- The texture from a `ParticleTextureModifier` is sliced into a grid as specified by the `FlipbookModifier`;
- Each frame, the renderer reads the `Attribute::SRITE_INDEX` of the particle and selects the Nth sprite in the spritesheet.
There is currently no built-in animation of `Attribute::SPRITE_INDEX`; instead you should use the Expression API to update the attribute each frame. This allows total control on the animation speed / framerate, any looping, or even allows non-linear framerate and complex indexing into the spritesheet.
Fixes #108
> Add flipbook animation

- src/render/mod.rs
- src/test_utils.rs
This assert can fail with an error like this in practice:
```
thread 'Compute Task Pool (8)' panicked at /home/sludge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_hanabi-0.8.0/src/render/mod.rs:211:9:
assertion `left == right` failed
left: Vec4(-0.0, -0.0, -0.0, 1.0000001)
right: Vec4(0.0, 0.0, 0.0, 1.0)
```
Change it to a `assert_approx_eq!` to fix that.
> Change `debug_assert_eq` to `assert_approx_eq`

- CHANGELOG.md
- Cargo.toml
- examples/spawn.rs
- examples/spawn_on_command.rs
- src/bundle.rs
- src/lib.rs
- src/plugin.rs
- src/properties.rs
- src/render/batch.rs
- src/render/mod.rs
Split the dynamic runtime storage of property values away from `CompiledParticleEffect`, which is an implementation detail, into a new `EffectProperties` component. This component manages access to property values by the user, as well as automated synchronization with the underlying `EffectAsset` when the list of declared properties changes.
This change adds a new `EffectSystems::UpdatePropertiesFromAsset` set during which the automated property update is performed. The set runs in Bevy's own `UpdateAssets` schedule, before `Update`.
As a consequence, change detection on properties now works as expected, and properties are only (re-)uploaded to GPU when the new `EffectProperties` component changed, instead of every frame as this was the case before this change. The component is also …
> Split runtime properties into `EffectProperties`

- CHANGELOG.md
- src/attributes.rs
- src/lib.rs
- src/plugin.rs
- src/properties.rs
- src/spawn.rs
Add more custom attributes for all float vector variants.
Move `EffectProperties` into the `properties` module.
Make the `properties` and `attributes` modules public, and add some module level documentation for both features.
Fixes #262
> Add more custom attributes and docs

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/plugin.rs
- src/render/mod.rs
- src/render/shader_cache.rs
- src/render/vfx_common.wgsl
- src/render/vfx_indirect.wgsl
- src/render/vfx_init.wgsl
- src/render/vfx_render.wgsl
- src/render/vfx_update.wgsl
Move most shared WGSL code into an import module `vfx_common.wgsl`, and
document it. This ensures the code remains in sync between the various passes
(init/update/render) without needing some error-prone copy/paste, while making
the code easier to read too.
This change moves `naga` and `naga_oil` from being dev-only dependencies to
being proper crate dependencies. This is required to use `naga_oil`'s import
system, like `bevy_render`. This makes the change a breaking one.
> Move shared WGSL code to imported module

- src/render/mod.rs
- src/render/vfx_common.wgsl
- src/render/vfx_indirect.wgsl
- src/render/vfx_init.wgsl
- src/render/vfx_render.wgsl
- src/render/vfx_update.wgsl
Move all shader functions related to random to the shared `vfx_common` module, to avoid code duplication.
> Move rand functions to `vfx_common`

- src/graph/expr.rs
- src/modifier/accel.rs
- src/modifier/mod.rs
Ensure that the generated code within a function, which generally accesses the particle attribute struct via a pointer, is emitted with a pointer indirection.
This is a partial fix, as `make_fn()` could be called with a non-pointer attribute struct, which would break with the reverse error. However for now it's only called in the update context with a pointer.
Fixes #275
> Handle attribute pointer in functions

- CHANGELOG.md
- src/lib.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/vfx_render.wgsl
Split the calculation of the particle orientation (generally, from `OrientModifier`) and its size (_e.g._ from `SizeOverLifetimeModifier`) in such a way they become independent, and we can mix and match orientations with screen space size or simulation space size.
Fix screen space size to avoid a perspective divide, which was effectively breaking the depth-independent property of the size.
Fixes #269
> Split render orientation and size

- CHANGELOG.md
- Cargo.toml
- examples/init.rs
- examples/spawn_on_command.rs
- src/lib.rs
- src/modifier/mod.rs
- src/modifier/output.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/vfx_render.wgsl
Remove the hard-coded path for scree-space size, and the field in `RenderContext`, and add instead a `ScreenSpaceSizeModifier`. Convert the previously hard-coded render shader code to a regular render modifier, now that the screen-space size calculation is decoupled from the orientation.
> Switch screen space size to be a modifier

- CHANGELOG.md
- src/graph/expr.rs
- src/lib.rs
Before this patch, the following code:
```
SetAttributeModifier::new(Attribute::COLOR, module.lit(0xffffffffu32))
```
would panic with:
```
2024-02-26T03:17:31.630083Z ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: failed to convert expression to a concrete type: the concrete type `i32` cannot represent the abstract value `4294967295` accurately
┌─ hanabi/worms_15332001714877325580.wgsl:83:18
│
83 │ particle.color = 4294967295;
│                  ^^^^^^^^^^ this expression has type {AbstractInt}
│
= failed to convert expression to a concrete type: the concrete type `i32` cannot represent the abstract value `4294967295` accurately
```
This one-character change fixes the issue.
> Fix invalid WGSL for large `u32` values

- CHANGELOG.md
- src/graph/mod.rs
Change the signature of the `VectorValue::new_uvecX()` functions to directly take a glam math type `UVecX`, like all other vectors of other scalar types.
> Change `VectorValue::new_uvecX()` to take `UVecX`

- CHANGELOG.md
- src/graph/mod.rs
Add missing `VectorValue::as_uvecX()` cast functions for unsigned integral vectors, and the `impl From<UVecX>`.
> Add missing `VectorValue::as_uvecX()` and `From`

- src/lib.rs
Fix a regression in the flipbook shader code where some variable previously emitted as `i32` by error instead of its actual `u32` type is now producing the correct literal value, resulting in an invalid shader operation between mismatching operand types. Cast the value to `i32` explicitly before emitting the shader code to ensure the value is emitted in the expected type.
> Fix regression in flipbook

- CHANGELOG.md
- src/graph/expr.rs
Add the missing `sqrt` (square root) and `inverseSqrt` (inverse square root) expressions to the Expression API.
> Add `sqrt` and `inverseSqrt` to Expression API

- CHANGELOG.md
- src/asset.rs
- src/graph/expr.rs
- src/graph/mod.rs
This change makes a few improvements to the serialized representation of an `EffectAsset`:
- `LiteralExpr`, `ExprHandle`, and `Module` are now `#[serde(transparent)]`, which makes them less verbose.
- `VectorValue` is serialized as its glam math type representation, making it a lot more readable in text format (_e.g._ RON).
Before:
```
module: (
expressions: [
Literal((
value: Vector((
vector_type: (
elem_type: Float,
count: 3,
),
storage: (1067030938, 3227307213, 1118770935, 0),
)),
)),
Literal((
value: Vector((
vector_type: (
elem_type: Bool,
count: 2,
),
storage: (0, 4294967295, 0, 0),
)),
)),
Binary(
op: Add,
left: (
index: 2,
),
right: (
index: 1,
),
),
],
),
```
After:
```
module: [
Literal(Vector(Vec3((1.2, -3.45, 87.54485)))),
Literal(Vector(BVec2((false, true)))),
Binary(
op: …
```
> Improve serialization format of `EffectAsset`

- src/graph/expr.rs
- src/lib.rs
- src/modifier/mod.rs
- src/plugin.rs
- src/render/mod.rs
- src/render/vfx_common.wgsl
- src/spawn.rs
- src/time.rs
~~Add a global time scale for all effects. Currently very WIP. Probably needs:~~
- ~~Some tests/examples~~
- ~~More docs~~
Now reimplemented (and documented) using the `Time<T>` resource from bevy.
(Could still need some examples/tests when we have settled on the design)
Closes #239. Pausing should be possible by setting `EffectTimeScale` to zero.
> Add a global time scale for all effects

- src/render/mod.rs
We were looping over all the particle groups in `emit_draw`, but we already call that function once per group. So we were actually drawing each group twice.
> Stop double-drawing each particle group.

- src/lib.rs
Ensure the `FLIPBOOK_ROW_COUNT` placeholder is emitted as `i32` so that the `vfx_render.wgsl` code taking the modulo with another `i32` is valid.
> Fix regression with flipbook

- CHANGELOG.md
- examples/force_field.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
- src/asset.rs
- src/graph/expr.rs
- src/modifier/accel.rs
- src/modifier/attr.rs
- src/properties.rs
Move the declaration of properties from `EffectAsset` into `Module`. Properties are only used in the context of expressions owned by a `Module`, so it makes more sense for them to be owned by the `Module` itself. This also forces them to be declared upfront with a type, which enables adding type checking during expression building (not in this change) instead of generating invalid shader code and only observing issues when actually spawning an effect.
> Move properties into `Module`

- CHANGELOG.md
- examples/activate.rs
- examples/force_field.rs
- examples/spawn_on_command.rs
- src/bundle.rs
- src/lib.rs
- src/render/mod.rs
- src/spawn.rs
Remove the override field `ParticleEffect::spawner`, and instead directly use the `EffectSpawner` component to override the spawner value(s) compared to the source `EffectAsset`. The extra indirection was a remanent of the time `EffectSpawner` didn't exist, but it makes little sense currently, and only complexifies things.
> Remove `ParticleEffect::spawner`

- CHANGELOG.md
- src/render/mod.rs
When rendering particles in alpha mask mode, there's no transparency involved; each fragment is either fully opaque or fully transparent. Therefore we can use the depth buffer, and don't need some fancy order independent transparency rendering or distance based sorting (which are not implemented).
This change enables depth writing when rendering particles through the `AlphaMask3d` render pass. This prevents particles from flickering, as visible in the `billboard.rs` example.
Partially fixes #183 (for non-transparent effects)
> Write to depth buffer in alpha mask mode

- src/graph/expr.rs
- src/render/vfx_common.wgsl
- src/render/vfx_init.wgsl
- src/render/vfx_render.wgsl
- src/render/vfx_update.wgsl
The documentation claims that `UniformRand` works with vectors, but it actually only works with scalars. This makes it hard to make particles with random colors, especially with the lack of dynamic `vec4` constructors.
This commit fixes the problem for float vectors only. It's still broken with matrices and non-float scalars, but those are less important.
> Make `BinaryOperator::UniformRand` work with vectors.

- Cargo.toml
- examples/ribbon.rs
- examples/worms.rs
- run_examples.bat
- run_examples.sh
- src/attributes.rs
- src/lib.rs
- src/modifier/clone.rs
- src/modifier/mod.rs
- src/modifier/ribbon.rs
- src/render/vfx_render.wgsl
This adds a new render modifier, the `RibbonModifier`. When it's present, quads are drawn between particles that are part of a trail created with the `CloneModifier`, instead of directly at the particle locations.
Internally, particles are threaded into a doubly linked list, with the `PREV` and `NEXT` attributes. I chose a linked list over fixed-size trails like the Unity VFX graph uses because (a) during ribbon rendering, a particle only needs to know the positions of its immediate neighbors; (b) linked lists better support variable-length trails. We need a doubly linked list instead of a singly linked list because (a) more sophisticated ribbon rendering will want to know about both the next and previous particles in order to implement line joins properly; (b) a singly linked list has …
> Implement simple ribbon rendering.

- CHANGELOG.md
- Cargo.toml
- src/plugin.rs
- src/render/aligned_buffer_vec.rs
- src/render/effect_cache.rs
- src/render/mod.rs
Increase the rendering performance by caching most bind groups across frames, and only regenerate them when any of the underlying buffers was re-allocated. Profiling with Tracy shows about 1ms saved on the `2d` example modified as per #272 (10'000 entities, 100 particle effects).
- The visibility check of entities now uses a `FixedBitSet`. There's no notable performance difference in itself in the above test, but using a bitfield saves some memory. The actual saving comes from using a `Local` parameter, which caches the bitset across system runs and prevent allocation/free each frame.
- Move `EffectCache` as a standalone resource on the render world. This is mostly for convenience to prevent issues with the borrow checked, as the `EffectsMeta` contains too many things.
- In …
> Cache bind group across frames

- CHANGELOG.md
- src/lib.rs
This fixes a panic in the extract code, where the `EffectAsset` was unloaded after the particle effect was compiled but before the extraction finished. The idea of using a weak handle was to avoid preventing the asset from unloading, but because
`CompiledParticleEffect` will anyway observe any change on the source `ParticleEffect` and its handle, clearing that handle will make `CompiledParticleEffect` also clear its own handle, even if strong, which will result in the asset being "freed" from references held by Hanabi.
Fixes #289
> Use strong handle in `CompiledParticleEffect`

- Cargo.toml
Remove the workaround for the Bevy dependency bug (bevyengine/bevy#11953) where some crates were not building unless an explicit dependency was added. This has been fixed in Bevy v0.13.1.
> Remove workaround for Bevy bug

- CHANGELOG.md
- src/attributes.rs
- src/graph/mod.rs
- src/graph/node.rs
The `MatrixValue` where C=3 require padding to 16 bytes, as per the WGSL specification. The padding was missing, leading to the wrong value being written for _e.g._ properties.
Fixes #310
> Fix missing padding of `mat3xR` in `MatrixValue`

- CHANGELOG.md
- examples/force_field.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
- src/bundle.rs
- src/lib.rs
- src/plugin.rs
- src/render/mod.rs
Fix effect properties being ignored because there's no `EffectProperties` component (and no code to auto-spawn it, despite the documentation stating otherwise). Require the component instead to be added always, and add it to `ParticleEffectBundle`. The alternative of auto-spawning is rendered complex by the fact the decision requires inspected the `EffectAsset`'s `Module` looking for properties, which requires multiple levels of indirection, so would be rather expensive to execute each frame on effects which doesn't require the component (so keep not having it and require to be re-checked each frame).
Fixes #309
> Fix effect properties ignored

- src/spawn.rs
I needed the ability to spawn an effect with a modified spawner, but these fields weren't accessible. This PR makes it possible to access those values.
I'm not sure if methods for this is the best approach, or if it makes more sense to make the fields public. I added both a getter method and set/with variants, since that matches the existing methods for `starts_active`.
> Add methods to access and modify spawner count/time

- .github/workflows/ci.yaml
- src/modifier/clone.rs
- src/plugin.rs
- src/render/buffer_table.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/vfx_common.wgsl
Fix the padding of all storage buffers to comply with the GPU device requirements, which on most Desktop platforms is 32 bytes, but can be different (for example on macOS M1 and later, it's generally 256 bytes). This fixes a number of issues where effects are not rendering at all, or display strong artifacts. The change is likely over-doing it by padding all structures used in arrays, however this can be optimized as a later pass.
Fix a bug in the `CloneModifier` where the shader code was allocating cloned particles without checking the buffer capacity, leading to underflow error and stomping over other parts of the buffer.
Re-enable buffer cleaning up on effect deletion, which was commented out during the ribbon change but not fixed, and left disabled. This caused the buffers to fill, …
> Fix storage padding and re-enable buffer clean-up

- src/render/mod.rs
- src/render/vfx_common.wgsl
- src/render/vfx_indirect.wgsl
Embed the element stride of various data structures directly into the `vfx_indirect` shader, instead of passing them at runtime through the `SpawnerParams` uniform buffer. Those strides are constants per GPU device, so cannot change after startup.
> Embed strides into shader

- src/render/mod.rs
- src/render/vfx_indirect.wgsl
Fix the number of workrgoups dispatched in the indirect dispatch pass when groups are used. Only the first group was counted.
Fixes #321
> Fix indirect dispatch count when groups are used

- src/attributes.rs
I'm assuming these are supposed to be `2`?
> fix typo in `Attribute`

- src/render/mod.rs
- src/render/vfx_indirect.wgsl
Fix some effects not updating after one or more effects have been deleted. This was due to the indirect pass shader assuming a contiguous `ParticleGroup` array, but that array contains gaps where effects have been deallocated, so updating a number of rows equal to the number of active effect means updating some unused rows and skipping some used ones in case there's any gap.
> Fix effects getting stuck after a deletion

- CHANGELOG.md
- src/render/vfx_update.wgsl
Fix a bug where the update compute pass is not seeded, so the PRNG returns the same sequence for all effect instances.
Fixes #333
> Seed the update compute pass

- src/graph/mod.rs
- src/render/mod.rs
- src/test_utils.rs
Only emit an error about failing to find an init or update pipeline if the pipeline creation state reports it failed. Otherwise (queued, creating) silently skip the frame until it's ready.
Fixes #341
> Only emit error if pipeline failed creation

- LICENSE
- README.md
Clarify the licensing without changing it, by deleting the `LICENSE` file and moving its content into `README.md` (this should help GitHub stop confusing that file for a third type of license). Also add some SPDX identifier for further clarity.
THIS DOESN'T CHANGE IN ANY WAY THE LICENSING TERMS; this is only a clarification.
> Clarify license with SPDX

- .github/workflows/ci.yaml
- Cargo.toml
- gpu_tests/empty_effect.rs
- src/bundle.rs
- src/lib.rs
- src/render/mod.rs
Prevent `extract_effects()` from attempting to `unwrap()` on an invalid asset handle, which causes a panic. Instead, use `filter_map()` to ignore compiled effects with an invalid handle. Add a regression test (no extraction) and an integration example of an empty effect to ensure there's no panic.
Fixes #343
> Avoid `unwrap()` on invalid asset

- CHANGELOG.md
- src/graph/expr.rs
Expose the `is_alive` flag of particles in the update pass, to enable an expression to query the current alive state of the particle.
> Expose `is_alive` particle flag

- src/asset.rs
- src/modifier/position.rs
- src/render/aligned_buffer_vec.rs
- src/render/buffer_table.rs
- src/render/effect_cache.rs
> Fix new linter: remove `std::mem::`

- .github/workflows/ci.yaml
- Cargo.toml
- src/asset.rs
- src/modifier/accel.rs
- src/modifier/attr.rs
- src/modifier/clone.rs
- src/modifier/force.rs
- src/modifier/kill.rs
- src/modifier/mod.rs
- src/modifier/output.rs
- src/modifier/position.rs
- src/modifier/ribbon.rs
- src/modifier/velocity.rs
- src/plugin.rs
Move the `Serialize` and `Deserialize` derives, based on `typetag`, under a new `serde` feature flag. This makes it possible to skip building with `typetag`, which for example is not compatible with `wasm` so would be a blocker for wasm support.
> Move ser/de under a feature flag

- src/render/mod.rs
- src/render/vfx_common.wgsl
Fix a bug where the render shader attempts to bind the `Spawner` storage buffer as read-only, but that struct is defined as containing an atomic variable, which according to the WGSL specification requires write access. Add a pipeline define `SPAWNER_READONLY` to redefine that struct field as non-atomic, to allow read-only binding.
> Fix shader binding bug

- examples/2d.rs
- examples/activate.rs
- examples/billboard.rs
- examples/circle.rs
- examples/force_field.rs
- examples/gradient.rs
- examples/init.rs
- examples/lifetime.rs
- examples/random.rs
- examples/spawn_on_command.rs
- examples/visibility.rs
The requesting of `VERTEX_WRITABLE_STORAGE` in all examples is a legacy from the very start of the project, which has no reason to be. We have already validated that everything works without it, and this creates confusion for users.
Fixes #317
> Remove `VERTEX_WRITABLE_STORAGE` from examples

- build_examples_wasm.sh
Mirror the bat script as a shell script.
> add shell equivalent to bat script

- CHANGELOG.md
- Cargo.toml
- build_examples_wasm.bat
- deny.toml
- examples/billboard.rs
- examples/circle.rs
- examples/gradient.rs
- examples/instancing.rs
- examples/worms.rs
- src/asset.rs
- src/graph/expr.rs
- src/lib.rs
- src/modifier/mod.rs
- src/modifier/output.rs
- src/modifier/ribbon.rs
- src/render/batch.rs
- src/render/mod.rs
- src/render/vfx_render.wgsl
Add a new `TextureSampleExpr` to allow sampling a texture from an expression. Make the `ParticleTextureModifier` use this. Change the texture image to be hosted on a new `EffectMaterial` component, and add `Module::add_texture()` to define a new texture slot (binding).
This is a primitive first version with several restrictions:
- Only color textures (those returning `vec4<f32>`), no depth.
- Only sampling via `textureSample()` in WGSL, no LOD or bias, no unsampled gather, _etc._
- No validation whatsoever about the coherence of the slots, the images on the material, and the expressions. If anything is inconsistent, this might produce runtime errors (fail to create shader) or simply render the wrong thing (no texture).
Fixes #355
> Add support for texture sampling as expression

- examples/2d.rs
- examples/activate.rs
- examples/billboard.rs
- examples/circle.rs
- examples/expr.rs
- examples/firework.rs
- examples/force_field.rs
- examples/gradient.rs
- examples/init.rs
- examples/instancing.rs
- examples/lifetime.rs
- examples/multicam.rs
- examples/ordering.rs
- examples/portal.rs
- examples/random.rs
- examples/ribbon.rs
- examples/spawn.rs
- examples/spawn_on_command.rs
- examples/utils/mod.rs
- examples/visibility.rs
- examples/worms.rs
Extract the creation of the Bevy app for all examples into a utility function. The app creation is somewhat interesting to look at once, but is otherwise very repetitive and clutters the examples with 20+ lines of code, removing the focus on the actual specifics a particular example is trying to demonstrate.
This change also ensures consistency across all examples, ensures they're returning an error code on termination if any error occurs (for CI), and make examples easier to maintain.
> Extract example app creation into utility function

- examples/utils/mod.rs
- src/render/mod.rs
Remove `EffectsMeta::indirect_dispatch_pipeline` which is duplicating the `DispatchIndirectPipeline` value for no good reason.
> Remove duplicate pipeline ref

- examples/worms.rs
- src/modifier/mod.rs
Fix a typo in the `worms.rs` example, making all worms move in the same direction instead of a random one.
Fixes #381
> Fix typo in worms example

- src/render/buffer_table.rs
- src/render/mod.rs
Clean-up and optimize `BufferTable<T>`:
- Change row counts to `u32` type; this helps a bit readability.
- Fix doc link.
- Use `mapped_at_creation` to upload the newly added data when a new `Buffer` is created, instead of doing some buffer copies. This ensures all new rows are copied in a single call, and makes better use of the WGPU staging buffer.
This change should not alter any behavior. It was originally a tentative workaround for some bug with Metal debugging, but proved useless for that purpose. However the minor optimization and code clean-up are nonetheless relevant.
> Optimize `BufferTable<T>`

- examples/ribbon.rs
I think this could be more helpful for people wanting to use the ribbon example. In my mind "tracers" are the most used application for this sort of thing, If you feel it isn't just close it.
run with:
`cargo run --example ribbon --features="bevy/bevy_winit bevy/bevy_pbr 3d bevy/bevy_gizmos"`
> change the ribbon example into a tracer example.

- Cargo.toml
- src/asset.rs
- src/plugin.rs
- src/render/aligned_buffer_vec.rs
- src/render/mod.rs
- src/render/vfx_common.wgsl
- src/spawn.rs
Move `wgpu` from a dev-dependency to a core crate dependency, to allow the direct use of its types.
Clean-up various documentations, and other minor code changes.
> Add `wgpu` as core dependency

- src/attributes.rs
- src/graph/expr.rs
- src/lib.rs
- src/modifier/attr.rs
- src/modifier/mod.rs
- src/plugin.rs
- src/render/buffer_table.rs
- src/render/effect_cache.rs
- Several asset-related errors now emit the asset name.
- `BufferTable` now emits a table name in its logs.
- Improved `ExprError` error messages by implementing `Display` for `ValueType`.
- `SetAttributeModifer::eval()` now attempts to check that the type of the value emitted by the expression, if available, matches the type of the attribute being assigned. This prevents generating invalid shader code.
> Improve debugging

- CHANGELOG.md
- Cargo.toml
- src/render/mod.rs
Fix a panic in the clone init pass due to some Vulkan validation error when using ribbons and trails. The indirect dispatch of the clone init pass used the wrong buffer offset, which in some cases was leading to an out of bound access, caught by the validation layer.
Fixes #399
> Fix panic in clone init pass

- src/render/mod.rs
- src/render/vfx_common.wgsl
- src/render/vfx_indirect.wgsl
Similar to the indirect update, the indirect render entry is dynamically allocated as a continuous slice. The current code was using the global effect index, which might be different. Adding an explicit entry into the particle group, similar to indirect dispatch, solves the issue.
Fixes #403
> Fix indirect render using the wrong index

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/plugin.rs
- src/render/batch.rs
- src/render/effect_cache.rs
- src/render/mod.rs
Start to transition the internal rendering implementation to leverage the retained render world introduced in Bevy 0.15.
This change moves the `CachedEffect` and `DispatchBufferIndices` out of the `EffectCache`, and convert them to components added to the render world entity spawned and synchronized via `SyncToRenderWorld` with the main world entity owning the effect instance.
As part of this change, split the addition and removal of new effect instances into a separate `add_remove_effects()` system which runs before the `prepare_effects()` system.
Also fix a small bug with opaque particles not rendered in some cases; this is hypothetical, but `EffectShaderSource::generate()` was not setting the `LayoutFlags::OPAQUE`.
> Start transitioning to retained render world

- src/plugin.rs
- src/render/batch.rs
- src/render/mod.rs
Retain the mesh and the properties of an effect instance into separate components (namely, `CachedMesh` and `CachedProperties`).
Directly process effect instances from extracted data, instead of inserting a modified representation (batch input) and processing that. This simplify the code and removes some unnecessary copies.
Split the batching operation (which currently doesn't batch anything) into a separate `batch_effects()` system, which reads all the cached effects directly from the ECS world, after `prepare_effects()` updated them from the extracted ones.
> Retain mesh and property into separate components

- src/render/batch.rs
- src/render/mod.rs
- src/spawn.rs
- Remove the unused `HashMap` for extracted effects, simply extract them into a `Vec`. We don't need the lookup anymore.
- Extract the `GlobalTransform` as is, and do any conversion to GPU transform later during processing when the main world is not locked.
> Clean-up extraction a bit

- CHANGELOG.md
- Cargo.toml
- gpu_tests/properties.rs
- src/lib.rs
- src/plugin.rs
- src/properties.rs
- src/render/aligned_buffer_vec.rs
- src/render/batch.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/property.rs
- src/render/vfx_common.wgsl
- src/render/vfx_indirect.wgsl
- src/render/vfx_init.wgsl
- src/render/vfx_render.wgsl
- src/render/vfx_update.wgsl
Split the properties from the `EffectCache` and move their resource management into a new `PropertyCache`, which allocates GPU buffers to store them. This clarifies ownership, and allows better batching (in theory) as not all effects use properties.
In this change, unfortunately for simplicity we directly store the offset into the property buffer for each instance into the effect batch, meaning we again block batching multiple effects. This is hopefully temporary (and not the only blocker, so doesn't introduce any regression), but makes the change incremental and easier to handle for now, while other clean-ups are still pending.
> Split properties into new `PropertyCache`

- CHANGELOG.md
- src/lib.rs
- src/plugin.rs
- src/render/aligned_buffer_vec.rs
- src/render/buffer_table.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/property.rs
Invalidate the bind groups for the simulation, containing the particle group buffer, when that buffer is reallocated or when the group changes position in the buffer. This was causing old buffers to be referenced when the group(s) changed, creating artifacts in ribbon rendering in particular.
Similarly, invalidate the bind groups referencing a property buffer when that buffer is reallocated, for the same reasons. This fixes a crash previously introduced by the new property buffer change.
> Invalidate more bind group on changes

- CHANGELOG.md
- src/graph/expr.rs
- src/lib.rs
- src/plugin.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/shader_cache.rs
- src/render/vfx_common.wgsl
Add a new `DebugSettings` resource controlling some debugging settings.
Add the ability via debugging settings to instruct a GPU debugger attached to the application to capture one or more GPU frames, either right now or each time a new effect is spawned.
> Add `DebugSettings` for GPU capture

- src/render/aligned_buffer_vec.rs
- src/render/buffer_table.rs
Always call `Buffer::destroy()` on the old buffer resource when a GPU buffer is re-allocated. This ensures we get a runtime assertion if a bind group is not recreated and attempts to use a stale buffer.
Fix a bug in `BufferTable` where the free list was not updated correctly, which could in theory lead to issues once re-allocating new elements.
> Destroy buffers after use, fix bug in `BufferTable`

- .github/workflows/ci.yaml
Examples are very slow on Windows agents because they use the software renderer. Use macOS agents with hardware GPUs instead.
> Run examples on macos-latest

- CHANGELOG.md
- docs/migration-v0.14-to-v0.15.md
- src/asset.rs
- src/lib.rs
- src/render/mod.rs
Add a new field to the effect asset, which determines the seed for the GPU side PRNG used in shader expressions. This value defaults to zero, making consecutive runs deterministic. This both gives better artistic control (what executes at runtime is what was authored), and helps with debugging by making repros consistent.
To restore the old behavior, assign a random value to the seed when creating the effect asset, _.e.g_ `prng_seed = rand::random::<u32>()`.
> Add `EffectAsset::prng_seed`

- CHANGELOG.md
- examples/2d.rs
- src/asset.rs
- src/lib.rs
- src/render/batch.rs
- src/render/mod.rs
- src/spawn.rs
Remove `ParticleEffect::z_layer_2d` in favor of just using the effect `Transform`'s Z coordinate. This makes ordering particle effects in layers (along Z) more consistent and expected.
Fixes #423
> Remove `z_layer_2d`

- .github/workflows/ci.yaml
- Cargo.toml
- deny.toml
- examples/ribbon.rs
- src/render/mod.rs
- src/render/sort.rs
- src/render/vfx_sort_copy.wgsl
Some sort compute pass were using a dynamic binding offset not a multiple of the device limit `min_storage_buffer_offset_alignment`. Instead of fixing the alignment, since the compute shader already adds a custom `u32` offset, use that offset to index precisely the dispatch indirect struct we want (12 bytes), and always bind the entire buffer with a zero binding offset.
Fixes #438
> Fix sort binding offset not aligned to device limit

- src/render/mod.rs
- src/render/vfx_common.wgsl
- src/render/vfx_indirect.wgsl
The effect metadata was maintaining a stale index to the spawner, which was incorrectly used in the indirect pass instead of using the same effect index as when read a few lines above. The effect metadata can't possibly maintain an index to the spawner because the former is lazily uploaded (and in fact this resets the effect, so should be almost never) while the latter is re-uploaded each frame and is always tightly packed (we reallocated the spawners each frame since anyway they change each frame).
Fixes #412
> Fix bug in indexing the spawner params

- CHANGELOG.md
- examples/2d.rs
- examples/activate.rs
- examples/circle.rs
- examples/expr.rs
- examples/firework.rs
- examples/force_field.rs
- examples/gradient.rs
- examples/init.rs
- examples/instancing.rs
- examples/lifetime.rs
- examples/multicam.rs
- examples/ordering.rs
- examples/portal.rs
- examples/random.rs
- examples/ribbon.rs
- examples/spawn.rs
- examples/visibility.rs
- examples/worms.rs
- src/asset.rs
- src/graph/expr.rs
- src/lib.rs
- src/modifier/output.rs
- src/spawn.rs
Change a few things to allow the `firework.rs` example to get a random color per firework explosion:
- Add `ColorBlendMode` and `ColorBlendMask` to enable color blending, and allow overlaying _e.g._ a `SetAttributeModifier(Attribute::COLOR)` with a `ColorOverLifetimeModifier`, without the former overwriting the latter. The blend mode determines the blend operation, while the blend mask determines which components are affected in the 4D vector.
- Add a new expression to combine a 3D vector and a scalar into a 4D vector. This allows recombining an RGB color with an Alpha value.
- Upload a different PRNG seed each frame because the GPU doesn't retain the PRNG state, so using the same seed each frame breaks randomness.
The `firework.rs` example has been updated to make use of all of this.
> Color changes to allow random firework colors

- Cargo.toml
- src/lib.rs
- src/plugin.rs
- src/render/mod.rs
There were two problems here:
1. The `ExtractComponentPlugin` for `EffectVisibilityClass` wasn't being
added, so the render world never got a chance to see
`EffectVisibilityClass`.
2. The Hanabi code was trying to query `RenderVisibleEntities` for
`CompiledParticleEffect` components, but those APIs expect to take a
visibility class instead.
I solved (1) by adding the plugin in the Hanabi plugin initialization,
and I solved (2) by switching `CompiledParticleEffect` calls to
`EffectVisibilityClass`. Making those changes causes particles to render
in Bevy 0.16.
> Fix visibility computation, allowing particles to appear in Bevy 0.16.

- src/attributes.rs
It's possible to run out if you use three `F32x3` attributes and velocity at the same time.
> Add another pad variable.

- src/render/event.rs
- src/render/mod.rs
This is currently not done, resulting in a crash when the arguments buffer resizes, which typically happens when multiple particle effects are spawned simultaneously.
There's a `todo!` that suggests that the original plan was to eagerly invalidate the init fill dispatch buffers when the arguments buffer changes size. I replaced this with usage of `CachedBindGroup` keyed off the ID of the arguments buffer, which seems to be the pattern used elsewhere in the code.
Closes #446.
> Recreate the init fill dispatch bind group when the arguments buffer resizes.

- src/render/mod.rs
Whenever a `CachedChildInfo` is created, then it must be "fixed up" via the `fixup_parents` system. That system uses a
`Changed<CachedParentInfo>` query filter to determine which parents it needs to process the children of. Usually, `resolve_parents` will regenerate the `CachedParentInfo` of every parent with a changed child, because the `is_child_list_changed` check will notice that the child entity IDs differ, and thus `fixup_parents` will pick up that newly-created `CachedParentInfo`. However, `resolve_parents` will skip regenerating the `CachedParentInfo` if the entity IDs of the children didn't change (as determined by `is_child_list_changed`). This means that, if the children changed but for whatever reason their *entity IDs* didn't, the change flag will never be set on the parent's …
> Mark `CachedParentInfo` as changed if any of the `CachedChildInfo` of that entity's children were changed.

- src/plugin.rs
- src/render/aligned_buffer_vec.rs
- src/render/batch.rs
- src/render/event.rs
- src/render/mod.rs
- src/render/vfx_utils.wgsl
Fix the source buffer offset for the init fill dispatch pass reading from the `GpuChildInfo` array the event count, and writing into the corresponding `GpuDispatchIndirect` struct the number of workgroups to dispatch to handle that number of events.
Remove the incorrect dependency to event buffers; the event buffers only store the events themselves, which are unused here. Instead, the init fill dispatch reads the event count, which is stored in the `GpuChildInfo` in a different buffer.
Remove the dedicated `init_fill_dispatch` compute kernel; instead we can use the generic `fill_dispatch` one since we're directly reading from and writing to uniform arrays.
Create a separate batching queue type `InitFillDispatchQueue` for the indirect init pass, which batches entries before they're …
> Fix `InitFillDispatchArgs` source offset

- CHANGELOG.md
- src/render/aligned_buffer_vec.rs
- src/render/effect_cache.rs
- src/render/event.rs
- src/render/mod.rs
- src/render/vfx_indirect.wgsl
Both the indirect init and indirect update buffers used complex data structures designed for CPU/GPU interaction. However those buffers are only ever used on GPU. Switch both of them to use `GpuBuffer`, which doesn't handle any CPU access and is therefore more simple and optimized (doesn't make any CPU -> GPU upload copy for example).
Fix a bug where an old buffer for CPU spawners was used after being reallocated, which caused a panic when submitting the render queue.
> Switch `GpuDispatchIndirect` buffers to `GpuBuffer`

- src/plugin.rs
- src/render/batch.rs
- src/render/mod.rs
Cache the mesh location allocated by Bevy for the `RenderMesh` assets into a new `CachedMeshLocation` component on the render world, and monitor any change to that location. On change, invalidate and re-upload the `GpuEffectMetadata` to ensure the indirect render arguments are up to date.
Fixes #450
> Update `GpuEffectMetadata` on mesh location update

- examples/firework.rs
- examples/worms.rs
- src/lib.rs
- src/modifier/mod.rs
This temporarily reverts commit 9f7c6de087c6ddd1df4c8076b15511be9892a652 to allow releasing a non-breaking hotfix. This will be re-applied after.
> Revert "Make the number of particles to emit in a GPU event an expression instead of a constant. (#444)"

- examples/firework.rs
- examples/worms.rs
- src/lib.rs
- src/modifier/mod.rs
This reverts commit d65cd725f25b20122c926b585d374ad91a404319, thereby re-applying commit 9f7c6de087c6ddd1df4c8076b15511be9892a652.
> Re-apply "Make the number of particles to emit in a GPU event an expression instead of a constant. (#444)"

- CHANGELOG.md
- src/asset.rs
- src/lib.rs
- src/render/gpu_buffer.rs
- src/spawn.rs
Add a new field `prng_seed` on the particle effect component, which enables overridding the default PRNG seed value inherited from the `EffectAsset` on a per-instance basis. This allows making truly random effect instances.
> Add `ParticleEffect::prng_seed`

- examples/init.rs
Particles in that example don't move. Having the default motion integration triggers a warning because there's no `VELOCITY` attribute on particles. Disable the motion integration to remove the warning, since motion integration is not needed.
> Disable motion integration in `init.rs` example

- src/lib.rs
- src/modifier/mod.rs
- src/render/effect_cache.rs
- src/render/mod.rs
- src/render/vfx_render.wgsl
Allow `RenderModifier`s fragment shader to access the `Particle` buffer (just like the vertex shader) with `RenderContext::set_needs_particle_fragment`
My use case is sampling a small part of a noise texture for each rendered particle
I want to sample a different part of the noise texture according to a seed
So i need access to the particle custom attributes in the fragment shader
let me know if it's worth upstreaming
> Add `particle` access in the fragment shader

- CHANGELOG.md
- Cargo.toml
- src/modifier/output.rs
Fix two bugs in codegen:
- `ColorBlendMask::to_component()` had a wrong `0..3` iterator for components, should be `0..=3` to include the Alpha one.
- `ColorOverLifetimeModifier` had a typo (double line ending), and was using some invalid WGSL construct (can't assign `color.rgb`, need to construct a full `vec4<f32>` then assign as a whole).
Fixes #479
> Fix codegen bugs around modifier and color mask

- CHANGELOG.md
- src/asset.rs
- src/graph/expr.rs
Gather attributes transitively used in expressions used in modifiers. This ensures the generated code is valid, and not referencing attributes not part of the `ParticleLayout`.
Fixes #440
> Transitively gather attributes from expressions

- src/render/aligned_buffer_vec.rs
- src/render/effect_cache.rs
- src/render/event.rs
- src/render/gpu_buffer.rs
- src/render/mod.rs
- src/render/property.rs
- src/render/sort.rs
- src/render/vfx_common.wgsl
- src/render/vfx_indirect.wgsl
- src/render/vfx_init.wgsl
- src/render/vfx_render.wgsl
- src/render/vfx_sort_copy.wgsl
- src/render/vfx_sort_fill.wgsl
- src/render/vfx_update.wgsl
Move the indirect draw args outside of `EffectMetadata`, and into a separate buffer of their own. This decouples the indirect draw args, which are largely driven by GPU, from the effect metadata, which are largely (and ideally, entirely) driven by CPU. The new indirect draw args buffer stores both indexed and non-indexed draw args, the latter padded with an extra `u32`. This ensures all entries are the same size and simplifies handling, but more importantly allows retaining a single unified dispatch of `vfx_indirect` for all effects without adding any extra indirection or having to split into two passes.
The main benefit is that this prevents resetting the effect when Bevy relocates the mesh, which requires re-uploading the mesh location info into the draw args (base vertex and/or first …
> Move indirect draw args to separate buffer
